version: '2.2'

services:
  mongo:
    image: mongo:4.2.0
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo/initdb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root